# Generated by Django 4.1.4 on 2023-02-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_payment_last_updated_payment_received_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('student', 'course')},
        ),
    ]
