# Generated by Django 4.1.4 on 2023-02-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='refered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
